### ISSUE TITLE
Many issues

### ISSUE THREAD

**Issue by mikegent01** [stuffi3000/Rise-of-Nations#21]
![image](https://user-images.githubusercontent.com/70764301/100694257-ae58e000-335c-11eb-991a-b509f9a7fc74.png)
Afghanistan tree is very powerfull
![image](https://user-images.githubusercontent.com/70764301/100694276-bca6fc00-335c-11eb-8c2b-35dc98d23e3b.png)
many events like this for afg, Afghanistan end up annexing most of the middle east 
![image](https://user-images.githubusercontent.com/70764301/100694279-be70bf80-335c-11eb-953f-da981b096496.png)
full annex raj
![image](https://user-images.githubusercontent.com/70764301/100695177-af8b0c80-335e-11eb-8d60-c5ea3df4fe50.png)
news.1302 in turkey
![image](https://user-images.githubusercontent.com/70764301/100695309-ecef9a00-335e-11eb-98b2-88425460e048.png)
some text needs fixing  news.1251 in tur
![image](https://user-images.githubusercontent.com/70764301/100695388-16102a80-335f-11eb-95b1-ee20aa87f2c5.png)
news.299 too vauge
![image](https://user-images.githubusercontent.com/70764301/100769162-ab480900-33c9-11eb-80ce-15eb27cf469d.png)
autonomy system broke

List :
- [x] Debuff Afghanistan Tree
- [x] Debuff Afghanistan Events 
- [x] Fix news.1302
- [x] Fix news.1251
- [x] Fix localization for news.299

**Comment by stuffi3000** [comment]
List :
[ ] Debuff Afghanistan Tree
[ ] Debuff Afghanistan Events 
[ ] Fix news.1302
[ ] Fix news.1251

**Comment by mikegent01** [comment]
![image](https://user-images.githubusercontent.com/70764301/100761063-72effd00-33c0-11eb-856d-a7d7eb185b57.png)

news.299 too vauge

**Comment by mikegent01** [comment]
fixed
