### ISSUE TITLE
MTG bug

### ISSUE THREAD

**Issue by mikegent01** [stuffi3000/Rise-of-Nations#39]
The same effect is used twice in MTG
![image](https://user-images.githubusercontent.com/70764301/106205652-d3b37000-618c-11eb-9f48-11b2c8936304.png)
![image](https://user-images.githubusercontent.com/70764301/106205758-fd6c9700-618c-11eb-8ba6-9dc9136a36c1.png)
![image](https://user-images.githubusercontent.com/70764301/106205774-065d6880-618d-11eb-845d-4a51f4083dce.png)

**Comment by antmrt** [comment]
The ability was referring to a non-existing JAP focus, should be fixed now
